## In this notebook we'll learn various ways to create array using NumPy buit-in functions

### Create an ndarray with a specified shape that is full of zeros

In [210]:
import numpy as np

zeros_array = np.zeros((2, 3))

In [211]:
print(' zeros_array : \n', zeros_array)
print('\n zeros_array has dimension:', zeros_array.shape)
print(' zeros_array is an object of type :', type(zeros_array))
print(' The elements in zeros_array are of type :', zeros_array.dtype)

 zeros_array : 
 [[0. 0. 0.]
 [0. 0. 0.]]

 zeros_array has dimension: (2, 3)
 zeros_array is an object of type : <class 'numpy.ndarray'>
 The elements in zeros_array are of type : float64


### Create an ndarray with a specified shape that is full of ones

In [212]:
ones_array = np.ones((2, 3))

In [213]:
print(' ones_array : \n', ones_array)
print('\n ones_array has dimension:', ones_array.shape)
print(' ones_array is an object of type :', type(ones_array))
print(' The elements in ones_array are of type :', ones_array.dtype)

 ones_array : 
 [[1. 1. 1.]
 [1. 1. 1.]]

 ones_array has dimension: (2, 3)
 ones_array is an object of type : <class 'numpy.ndarray'>
 The elements in ones_array are of type : float64


### Create an ndarray with a specified shape that is full of particular constant

In [214]:
full_array = np.full((2, 3), 3)

In [215]:
print(' full_array: \n', full_array)
print('\n full_array has dimension: ', full_array.shape)
print(' full_array is an object of type: ', type(full_array))
print(' The elements in full_array are of type: ', full_array.dtype)

 full_array: 
 [[3 3 3]
 [3 3 3]]

 full_array has dimension:  (2, 3)
 full_array is an object of type:  <class 'numpy.ndarray'>
 The elements in full_array are of type:  int32


### Create a identity matrix

In [216]:
identity_array = np.eye(3)

In [217]:
print('identity_array: ', identity_array)
print('\n identity_array has dimension: ', identity_array.shape)
print(' identity_array is an object of type: ', type(identity_array))
print(' The elements in identity_array are of type: ', identity_array.dtype)

identity_array:  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 identity_array has dimension:  (3, 3)
 identity_array is an object of type:  <class 'numpy.ndarray'>
 The elements in identity_array are of type:  float64


### Create a Diagonal matrix

In [218]:
diagonal_array = np.diag([2 ,3])

In [219]:
print(' diagonal_array: \n', diagonal_array)
print('\n diagonal_array has dimension: ', diagonal_array.shape)
print(' diagonal_array is an object of type: ', type(diagonal_array))
print(' The elements in diagonal_array are of type: ', diagonal_array.dtype)

 diagonal_array: 
 [[2 0]
 [0 3]]

 diagonal_array has dimension:  (2, 2)
 diagonal_array is an object of type:  <class 'numpy.ndarray'>
 The elements in diagonal_array are of type:  int32


### Create a evenly spaced array (within a given interval)

In [220]:
arange_array_a = np.arange(5)

In [221]:
print('\n arange_array_a: ', arange_array_a)
print(' arange_array_a has dimension: ', arange_array_a.shape)
print(' arange_array_a is an object of type: ', type(arange_array_a))
print(' The elements in arange_array_a are of type: ', arange_array_a.dtype)


 arange_array_a:  [0 1 2 3 4]
 arange_array_a has dimension:  (5,)
 arange_array_a is an object of type:  <class 'numpy.ndarray'>
 The elements in arange_array_a are of type:  int32


In [222]:
# np.arange(start, stop)
arange_array_b = np.arange(5, 10)

print('\n arange_array_b: \n', arange_array_b)

# np.arange(start, stop, step)
arange_array_c = np.arange(5, 10, 2)

print('\n arange_array_c: \n', arange_array_c)


 arange_array_b: 
 [5 6 7 8 9]

 arange_array_c: 
 [5 7 9]


### NumPy linspace function linspace(start, stop, N=50)

In [223]:
linspace_array = np.linspace(2, 10, 3)
print('\n linspace_array: \n', linspace_array)


 linspace_array: 
 [ 2.  6. 10.]


In [224]:
### NumPy reshape function

In [225]:
reshape_array_a = np.arange(0, 20, 2).reshape(2, 5)

In [226]:
print('\n reshape_array_a: \n', reshape_array_a)


 reshape_array_a: 
 [[ 0  2  4  6  8]
 [10 12 14 16 18]]


In [227]:
### NumPy normal function

In [228]:
normal_array = np.random.normal(0, 0.1, size=(5, 5))

In [229]:
print('\n normal_array: \n', normal_array)


 normal_array: 
 [[ 0.06271461  0.02182326 -0.1648869  -0.11664919  0.02524245]
 [-0.16357312  0.02737127 -0.01133025 -0.00408326 -0.00099903]
 [ 0.12467777 -0.09220197 -0.04724684 -0.05465412 -0.084702  ]
 [ 0.17696349 -0.02744352  0.07930023  0.03215985  0.02620604]
 [-0.07854299 -0.04431918  0.09689031  0.00863857 -0.05781096]]
