### Accessing, Deleting, and Inserting Elements Into Rank-2 ndarrays

In [34]:
## Import python numpy library
import numpy as np

## We create Rank-2 array using numpy function
rank2_array = np.arange(9).reshape(3,3)
print('rank2_array:\n ', rank2_array)

rank2_array:
  [[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Accessing rank2_array elements using positive indices

In [35]:
print(' Element at (0, 0) position in rank2_array: ', rank2_array[0, 0])
print(' Element at (1, 3) position in rank2_array: ', rank2_array[1, 2])

 Element at (0, 0) position in rank2_array:  0
 Element at (1, 3) position in rank2_array:  5


#### Accessing rank2_array elements using negative indices

In [36]:
print(' Element at (0, 0) position in rank2_array: ', rank2_array[-3, -3])
print(' Element at (1, 3) position in rank2_array: ', rank2_array[-2, -1])

 Element at (0, 0) position in rank2_array:  0
 Element at (1, 3) position in rank2_array:  5


#### Update particular element in rank2_array ndarray

In [37]:
print(' Element at (0, 0) position before update: ', rank2_array[-3, 0])
rank2_array[-3, 0] = 11
print(' Element at (0, 0) position after update: ', rank2_array[-3, 0])

 Element at (0, 0) position before update:  0
 Element at (0, 0) position after update:  11


#### Delete row in rank2_array ndarray

In [38]:
## Delete 2nd and 3rd row in rank2_array ndarray
print(' rank2_array ndarray, before deleting 2nd and 3rd rows: \n', rank2_array)
rank2_array_del_a = np.delete(rank2_array, [1, 2], axis=0)
print('\n new ndarray, after deleting 2nd and 3rd rows: \n', rank2_array_del_a)

 rank2_array ndarray, before deleting 2nd and 3rd rows: 
 [[11  1  2]
 [ 3  4  5]
 [ 6  7  8]]

 new ndarray, after deleting 2nd and 3rd rows: 
 [[11  1  2]]


In [39]:
#### Delete column in rank2_array ndarray

In [40]:
## Delete 1st and 3rd column in rank2_array ndarray
print(' rank2_array ndarray, before deleting 1st and 3rd columns: \n', rank2_array)
rank2_array_del_b = np.delete(rank2_array, [0, 2], axis=1)
print('\n new ndarray, after deleting 1st and 3rd columns: \n', rank2_array_del_b)

 rank2_array ndarray, before deleting 1st and 3rd columns: 
 [[11  1  2]
 [ 3  4  5]
 [ 6  7  8]]

 new ndarray, after deleting 1st and 3rd columns: 
 [[1]
 [4]
 [7]]
