### Arithmetic operations and Broadcasting

In [177]:
import numpy as np

#### Aithmatic operation on Rank-1 array

In [178]:
ndarray_a = np.array([1, 2, 3, 4])
ndarray_b = np.array([4, 6, 7, 8])

#### Rank-1 ndarray Addition

In [179]:
ndarray_addition = np.add(ndarray_a, ndarray_b)
print(' ndarray_addition: \n', ndarray_addition)

 ndarray_addition: 
 [ 5  8 10 12]


#### Rank-1 ndarray Subtraction

In [180]:
ndarray_subtraction = np.subtract(ndarray_a, ndarray_b)
print(' ndarray_subtraction: \n', ndarray_subtraction)

 ndarray_subtraction: 
 [-3 -4 -4 -4]


#### Rank-1 ndarray Division

In [181]:
ndarray_division = np.divide(ndarray_a, ndarray_b)
print(' ndarray_division: \n', ndarray_division)

 ndarray_division: 
 [0.25       0.33333333 0.42857143 0.5       ]


#### Rank-1 ndarray Multiplication

In [182]:
ndarray_multiplication = np.multiply(ndarray_a, ndarray_b)
print(' ndarray_multiplication: \n', ndarray_multiplication)

 ndarray_multiplication: 
 [ 4 12 21 32]


### Airthmatic operation on Rank-2 array

In [183]:
# We'll define two Rank-2 array to implement Rank-2 ndarray airthmatic operations
ndarray_r2_a = np.arange(6).reshape(3, 2)
ndarray_r2_b = np.arange(5, 11).reshape(3, 2)

print(' ndarray_r2_a:\n', ndarray_r2_a)
print('\n ndarray_r2_b:\n', ndarray_r2_b)

 ndarray_r2_a:
 [[0 1]
 [2 3]
 [4 5]]

 ndarray_r2_b:
 [[ 5  6]
 [ 7  8]
 [ 9 10]]


#### Rank-2 ndarray Addition

In [184]:
ndarray_r2_addition = np.add(ndarray_r2_a, ndarray_r2_b)
print(' ndarray_r2_addition: \n', ndarray_r2_addition)

 ndarray_r2_addition: 
 [[ 5  7]
 [ 9 11]
 [13 15]]


#### Rank-2 ndarray Subtraction

In [185]:
ndarray_r2_subtration = np.subtract(ndarray_r2_a, ndarray_r2_b)
print(' ndarray_r2_subtration: \n', ndarray_r2_subtration)

 ndarray_r2_subtration: 
 [[-5 -5]
 [-5 -5]
 [-5 -5]]


#### Rank-2 ndarray Division

In [186]:
ndarray_r2_divide = np.divide(ndarray_r2_a, ndarray_r2_b)
print(' ndarray_r2_divide: \n', ndarray_r2_divide)

 ndarray_r2_divide: 
 [[0.         0.16666667]
 [0.28571429 0.375     ]
 [0.44444444 0.5       ]]


#### Rank-2 ndarray Multiplication

In [187]:
ndarray_r2_multiply = np.multiply(ndarray_r2_a, ndarray_r2_b)
print(' ndarray_r2_multiply: \n', ndarray_r2_multiply)

 ndarray_r2_multiply: 
 [[ 0  6]
 [14 24]
 [36 50]]


#### ndarray exponentioal airthmatic operation

In [188]:
ndarray_expo = np.array([2, 4, 6, 8])
ndarray_expo_res = np.power(ndarray_expo, 2)

print(' ndarray_expo_res: \n', ndarray_expo_res)

 ndarray_expo_res: 
 [ 4 16 36 64]


#### ndarray sqrt airthmatic operation

In [189]:
ndarray_sqrt = np.array([2, 4, 6, 8])
ndarray_sqrt_res = np.sqrt(ndarray_sqrt)

print(' ndarray_sqrt_res: \n', ndarray_sqrt_res)

 ndarray_sqrt_res: 
 [1.41421356 2.         2.44948974 2.82842712]


#### ndarray exponential airthmatic operation

In [190]:
ndarray_exp = np.array([2, 4, 6, 8])
ndarray_exp_res = np.exp(ndarray_exp)

print(' ndarray_exp_res: \n', ndarray_exp_res)

 ndarray_exp_res: 
 [   7.3890561    54.59815003  403.42879349 2980.95798704]
