### Boolean Indexing, Set Operations, and Sorting

In [32]:
# Import python NumPy library
import numpy as np

ndarray_a = np.arange(25)
print(' ndarray_a : \n', ndarray_a)

 ndarray_a : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


##### Do slice ndarray_a based on boolean indexing

In [33]:
## Get ndarray elements that are less than 15
sliced_ndarray_a = ndarray_a[ndarray_a < 15]
print('\n sliced_ndarray_a : ', sliced_ndarray_a)


 sliced_ndarray_a :  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [34]:
## Get ndarray elements that are greater than 15
sliced_ndarray_b = ndarray_a[ndarray_a > 15]
print('\n sliced_ndarray_b : ', sliced_ndarray_b)


 sliced_ndarray_b :  [16 17 18 19 20 21 22 23 24]


In [35]:
## Update ndarray elements those are even with value 22
ndarray_a[ndarray_a % 2 == 0] = 22
print('\n ndarray_a : ', ndarray_a)


 ndarray_a :  [22  1 22  3 22  5 22  7 22  9 22 11 22 13 22 15 22 17 22 19 22 21 22 23
 22]


#### Set operations

In [36]:
set_ndarray_a = np.arange(6)
set_ndarray_b = np.arange(3, 9)
print('set_ndarray_a: \n', set_ndarray_a)
print('set_ndarray_b: \n', set_ndarray_b)

set_ndarray_a: 
 [0 1 2 3 4 5]
set_ndarray_b: 
 [3 4 5 6 7 8]


##### Intersection operation

In [37]:
intersection_ndarray = np.intersect1d(set_ndarray_a,set_ndarray_b)
print(' intersection_ndarray: \n', intersection_ndarray)

 intersection_ndarray: 
 [3 4 5]
