### Accessing, Deleting, and Inserting Elements Into Rank-2 ndarrays
___

In [268]:
## Import python numpy library
import numpy as np

## We create Rank-2 array using numpy function
rank2_array = np.arange(9).reshape(3,3)
print('rank2_array:\n ', rank2_array)

rank2_array:
  [[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Accessing rank2_array elements using positive indices

In [269]:
print(' Element at (0, 0) position in rank2_array: ', rank2_array[0, 0])
print(' Element at (1, 3) position in rank2_array: ', rank2_array[1, 2])

 Element at (0, 0) position in rank2_array:  0
 Element at (1, 3) position in rank2_array:  5


#### Accessing rank2_array elements using negative indices

In [270]:
print(' Element at (0, 0) position in rank2_array: ', rank2_array[-3, -3])
print(' Element at (1, 3) position in rank2_array: ', rank2_array[-2, -1])

 Element at (0, 0) position in rank2_array:  0
 Element at (1, 3) position in rank2_array:  5


#### Update particular element in rank2_array ndarray

In [271]:
print(' Element at (0, 0) position before update: ', rank2_array[-3, 0])
rank2_array[-3, 0] = 11
print(' Element at (0, 0) position after update: ', rank2_array[-3, 0])

 Element at (0, 0) position before update:  0
 Element at (0, 0) position after update:  11


#### Delete row in rank2_array ndarray
##### Delete 2nd and 3rd row in rank2_array ndarray

In [272]:
print(' rank2_array ndarray, before deleting 2nd and 3rd rows: \n', rank2_array)
rank2_array_del_a = np.delete(rank2_array, [1, 2], axis=0)
print('\n new ndarray, after deleting 2nd and 3rd rows: \n', rank2_array_del_a)

 rank2_array ndarray, before deleting 2nd and 3rd rows: 
 [[11  1  2]
 [ 3  4  5]
 [ 6  7  8]]

 new ndarray, after deleting 2nd and 3rd rows: 
 [[11  1  2]]


#### Delete column in rank2_array ndarray
#####     Delete 1st and 3rd column in rank2_array ndarray

In [273]:
print(' rank2_array ndarray, before deleting 1st and 3rd columns: \n', rank2_array)
rank2_array_del_b = np.delete(rank2_array, [0, 2], axis=1)
print('\n new ndarray, after deleting 1st and 3rd columns: \n', rank2_array_del_b)

 rank2_array ndarray, before deleting 1st and 3rd columns: 
 [[11  1  2]
 [ 3  4  5]
 [ 6  7  8]]

 new ndarray, after deleting 1st and 3rd columns: 
 [[1]
 [4]
 [7]]


#### Append elements to ndarray
##### Append elements to row in rank2_array

In [274]:
print(' rank2_array ndarray before appending elements in row: \n', rank2_array)
append_rank2_array = np.append(rank2_array, [[21, 22, 23]], axis=0)
print('\n append_rank2_array ndarray after appending elements in row: \n', append_rank2_array)

 rank2_array ndarray before appending elements in row: 
 [[11  1  2]
 [ 3  4  5]
 [ 6  7  8]]

 append_rank2_array ndarray after appending elements in row: 
 [[11  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [21 22 23]]


##### Append elements to columns in rank2_array

In [275]:
print(' rank2_array ndarray before appending elements in column: \n', rank2_array)
append_rank2_array_col = np.append(rank2_array, [[41], [42], [43]], axis=1)
print('\n append_rank2_array ndarray after appending elements in column: \n', append_rank2_array_col)

 rank2_array ndarray before appending elements in column: 
 [[11  1  2]
 [ 3  4  5]
 [ 6  7  8]]

 append_rank2_array ndarray after appending elements in column: 
 [[11  1  2 41]
 [ 3  4  5 42]
 [ 6  7  8 43]]


##### Insert column to rank2_array

In [276]:
print(' rank2_array ndarray before inserting column: \n', rank2_array)
insert_rank2_array_col = np.insert(rank2_array, 1, [41, 42, 43], axis=1)
print('\n insert_rank2_array_col ndarray after inserting column: \n', insert_rank2_array_col)

 rank2_array ndarray before inserting column: 
 [[11  1  2]
 [ 3  4  5]
 [ 6  7  8]]

 insert_rank2_array_col ndarray after inserting column: 
 [[11 41  1  2]
 [ 3 42  4  5]
 [ 6 43  7  8]]


#### Stack ndarray vertically

In [277]:
print(' rank2_array ndarray : \n', rank2_array)
rank2_array_vstack = np.vstack((rank2_array, [71, 72, 73]))
print('\n After stacking horizontally rank2_array_vstack ndarray : \n', rank2_array_vstack)


 rank2_array ndarray : 
 [[11  1  2]
 [ 3  4  5]
 [ 6  7  8]]

 After stacking horizontally rank2_array_vstack ndarray : 
 [[11  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [71 72 73]]


#### Stack ndarray horizontally

In [278]:
print(' rank2_array ndarray : \n', rank2_array)
rank2_array_hstack = np.hstack((rank2_array, [[71], [72], [73]]))
print('\n After stacking horizontally rank2_array_hstack ndarray : \n', rank2_array_hstack)

 rank2_array ndarray : 
 [[11  1  2]
 [ 3  4  5]
 [ 6  7  8]]

 After stacking horizontally rank2_array_hstack ndarray : 
 [[11  1  2 71]
 [ 3  4  5 72]
 [ 6  7  8 73]]
