### Slicing Rank-2 ndarrays

In [63]:
## Import python NumPy library
import numpy as np
ref_array = np.arange(20).reshape(4, 5)
print('ref_array: \n', ref_array)

ref_array: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


#### Demo of ndarray[start:end] for Rank-2 ndarray

In [64]:
sliced_array_i = ref_array[1:2, 1:3]
print(' sliced_array_i: \n', sliced_array_i)

 sliced_array_i: 
 [[6 7]]


#### Demo of ndarray[:end] for Rank-2 ndarray

In [65]:
sliced_array_ii = ref_array[:2, :3]
print(' sliced_array_ii: \n', sliced_array_ii)

 sliced_array_ii: 
 [[0 1 2]
 [5 6 7]]


#### Demo of ndarray[start:] for Rank-2 ndarray

In [66]:
sliced_array_iii = ref_array[2:, 2:]
print(' sliced_array_iii: \n', sliced_array_iii)

 sliced_array_iii: 
 [[12 13 14]
 [17 18 19]]


In [67]:
print('ref_array before updating one of it\'s sliced ndarray (sliced_array_iii): \n', ref_array)
sliced_array_iii[0, 0] = 112
print('\nref_array after updating one of it\'s sliced ndarray (sliced_array_iii): \n', ref_array)

ref_array before updating one of it's sliced ndarray (sliced_array_iii): 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

ref_array after updating one of it's sliced ndarray (sliced_array_iii): 
 [[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11 112  13  14]
 [ 15  16  17  18  19]]


#### Demo of ndarray[start:end].copy() method for Rank-2 ndarray

In [68]:
sliced_array_iii_a = ref_array[2:, 2:].copy()
print(' sliced_array_iii_a: \n', sliced_array_iii)

 sliced_array_iii_a: 
 [[112  13  14]
 [ 17  18  19]]


In [69]:
print('ref_array before updating one of it\'s sliced ndarray (sliced_array_iii_a): \n', ref_array)
sliced_array_iii_a[0, 0] = 113
print('\nref_array after updating one of it\'s sliced ndarray (sliced_array_iii_a): \n', ref_array)

ref_array before updating one of it's sliced ndarray (sliced_array_iii_a): 
 [[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11 112  13  14]
 [ 15  16  17  18  19]]

ref_array after updating one of it's sliced ndarray (sliced_array_iii_a): 
 [[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11 112  13  14]
 [ 15  16  17  18  19]]


#### Demo of ndarray[indices, start:end] for Rank-2 ndarray where indices is Rank-1 ndarray

In [70]:
indices = np.arange(2)
print(' indices : \n', indices)

sliced_array_iv = ref_array[indices, 0:3]
print('\n ref_array: \n', ref_array)

print('\n sliced_array_iv: \n', sliced_array_iv)

 indices : 
 [0 1]

 ref_array: 
 [[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11 112  13  14]
 [ 15  16  17  18  19]]

 sliced_array_iv: 
 [[0 1 2]
 [5 6 7]]
