#### Determining SPAN computationally

In [2]:
# Make python package NumPy available using import method
import numpy as np

# Creates matrix t (right side of the augmented matrix).
t = np.array([4, 11])

# Creates matrix vw (left side of the augmented matrix).
vw = np.array([[1, 2], [3, 5]])

# Prints vw and t
print("\nVector vw:", vw, "\nVector t:", t, sep="\n")



Vector vw:
[[1 2]
 [3 5]]

Vector t:
[ 4 11]


In [3]:
def check_vector_span(set_of_vectors, vector_to_check):
    # Creates an empty vector of correct size
    vector_of_scalars = np.asarray([None]*set_of_vectors.shape[0])
    try:
        vector_of_scalars = np.linalg.solve(set_of_vectors, vector_to_check)
        if not (vector_of_scalars is None):
            print("\nVector is within span.\nScalars in s:", vector_of_scalars)
    except Exception as exception_type:
        if str(exception_type) == "Singular matrix":
            print("\nNo single solution\nVector is NOT within span")
        else:
            print("\nUnexpected Exception Error:", exception_type)
    return vector_of_scalars


Vector is within span.
Scalars in s: [2. 1.]


In [4]:
# Call to check_vector_span to check either vector t is within span of vectors vw

print("\nEquation 1:\n Matrix vw:", vw, "\nVector t:", t, sep="\n")
s = check_vector_span(vw,t)



Equation 1:
 Matrix vw:
[[1 2]
 [3 5]]

Vector t:
[ 4 11]

Vector is within span.
Scalars in s: [2. 1.]


In [6]:
# Call to check a new set of vectors vw2 and t2
vw2 = np.array([[1, 2], [2, 4]])
t2 = [6, 12]

print("\nEquation 2:\n Matrix vw2:", vw2, "\nVector t2:", t, sep="\n")
s2 = check_vector_span(vw2,t2)


Equation 2:
 Matrix vw2:
[[1 2]
 [2 4]]

Vector t2:
[ 4 11]

No single solution
Vector is NOT within span
