In [286]:
import numpy as np
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt

%matplotlib inline

In [287]:
csv_data = pd.read_csv('./lect_11_b_perceptron_algorithm.csv')

In [288]:
# Get csv_data initial <N> rows
csv_data.head(2)

0.78051  -0.063669  1
0  0.28774    0.29139  1
1  0.40714    0.17878  1

In [289]:
# How to extract 0th, 1st index columns from csv_data
zero_one_index_columns = csv_data.iloc[ : , [0, 1]]
zero_one_index_columns_array_ref = np.array(zero_one_index_columns)
zero_one_index_columns_array = np.array(zero_one_index_columns)[0:4]
print(zero_one_index_columns_array)
#print(zero_one_index_columns_array_ref)

[[0.28774 0.29139]
 [0.40714 0.17878]
 [0.2923  0.4217 ]
 [0.50922 0.35256]]


In [290]:
two_index_columns = csv_data.iloc[ : , [2]]
two_index_columns_array_ref = np.array(two_index_columns)
two_index_columns_array = np.array(two_index_columns)[0:2]
#print(two_index_columns_array)
#print(two_index_columns_array_ref)

In [291]:
# Uncomment below line to observe transposed matrix of csv_data using index 0
t0 = zero_one_index_columns_array.T[0]
print(t0)

[0.28774 0.40714 0.2923  0.50922]


In [292]:
# Uncomment below line to observe transposed matrix of csv_data using index 2
t1 = zero_one_index_columns_array.T[1]
print(t1)

[0.29139 0.17878 0.4217  0.35256]


In [293]:
# Get minimum value of transposed csv_data
#print(min(csv_data.T[0]))
# Get minimum value of transposed csv_data
#print(max(csv_data.T[0]))

In [294]:
# Get minimum value of transposed csv_data
#print(min(csv_data.T[1]))
# Get minimum value of transposed csv_data
#print(max(csv_data.T[1]))